server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://172.16.98.129:13306/columnstore_info?useUnicode=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: china123
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  mapper-locations: classpath*:net/chinaedu/datacenterservice/mapper/**/*Mapper.xml
  type-aliases-package: net.chinaedu.datacentercore.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
