server:
  port: 8082
spring:
  datasource:
    url: jdbc:mysql://172.16.98.153:3306/cuijz_test?useUnicode=true&useSSL=false&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: chinaedu
    password: chinaedu
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      field-strategy: not_empty
      column-underline: true
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: false
  mapper-locations: classpath*:net/chinaedu/datacenterservice/mapper/**/*Mapper.xml
  type-aliases-package: net.chinaedu.datacentercore.domain
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
